apiVersion: v1
kind: Service
metadata:
  name: cicada-mysql-service
  labels:
    app: cicada-mysql
spec:
  type: NodePort
  selector:
    app: cicada-mysql
  ports:
    - protocol: TCP
      nodePort: 30306
      port: 3306
      targetPort: 3306