apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicada-judge-deployment
  labels:
    app: cicada-judge
spec:
  selector:
    matchLabels:
      app: cicada-judge
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cicada-judge
    spec:
      containers:
        - image: cicada-judge
          name: cicada-judge-container
          imagePullPolicy: Never
          env:
            # 环境变量
            - name: MYSQL_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: cicada-secret
                  key: MYSQL_USER_NAME
            - name: MYSQL_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cicada-secret
                  key: MYSQL_USER_PASSWORD
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: cicada-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: cicada-config
                  key: MYSQL_PORT
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: cicada-config
                  key: MYSQL_DATABASE
          ports:
            - containerPort: 80
              name: portname
          volumeMounts:
            - name: cicada-judge-persistentstorage
              mountPath: /app/logs
      volumes:
        - name: cicada-judge-persistentstorage
          persistentVolumeClaim:
            claimName: cicada-judge-pvclaim
