apiVersion: v1
kind: Service
metadata:
  name: cicada-judge-service
  labels:
    app: cicada-judge
spec:
  type: NodePort
  selector:
    app: cicada-judge
  ports:
    - protocol: TCP
      nodePort: 32080
      port: 80
      targetPort: 8080