apiVersion: v1
kind: Service
metadata:
  name: cicada-alarm-service
  labels:
    app: cicada-alarm
spec:
  type: NodePort
  selector:
    app: cicada-alarm
  ports:
    - protocol: TCP
      nodePort: 32080
      port: 80
      targetPort: 8080